const {readFileSync, writeFileSync} = require('fs')

const first = readFileSync('./constant/first.txt', 'utf8')
const second = readFileSync('./constant/second.txt', 'utf8')

writeFileSync(
    './constant/autogenerate.txt',
    `Here is the autogenerated file using write filesync: ${first}, ${second}`,
    { flag: 'a'}
)